version: '2.2'
services:
  postgresql:
    image: 'postgres:latest'
    container_name: postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nopass
    networks:
      - travel_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  diesel-test:
    build:
      dockerfile: DockerAuth
      context: .
    container_name: diesel-test
    links:
      - postgresql
    networks:
      - travel_bot
    ports:
      - "3003:3003"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres://admin:nopass@postgresql:5432
volumes:
  postgres_data:
networks:
  travel_bot:
    external: true
